import { NextResponse } from 'next/server';
import { getSessionUser } from '@/lib/auth/session';
import { getProfile, getJournalEntries, getSymptomAssessments, getLabReports, getUserConversations } from '@/lib/db/repository';

export async function GET() {
  try {
    const session = await getSessionUser();
    if (!session) {
      return NextResponse.json({ error: 'Authentication required' }, { status: 401 });
    }

    const [profile, journals, assessments, labReports, conversations] = await Promise.all([
      getProfile(session.id),
      getJournalEntries(session.id),
      getSymptomAssessments(session.id),
      getLabReports(session.id),
      getUserConversations(session.id),
    ]);

    // Format consolidated health awareness summary
    const summary = {
      generatedAt: new Date().toISOString(),
      platform: 'Swasth AI 2.0 — Advanced AI Health Awareness Platform',
      user: {
        email: session.email,
        name: session.name || 'Anonymous User',
        profile: profile || {},
      },
      healthVitalsSummary: {
        recentJournalCount: journals.length,
        recentEntries: journals.slice(0, 5),
        averageSleepHours: journals.length > 0
          ? (journals.reduce((acc: number, j: any) => acc + (j.sleepHours || 0), 0) / journals.filter((j: any) => j.sleepHours).length || 1).toFixed(1)
          : 'N/A',
      },
      symptomAssessments: assessments.slice(0, 5).map((a: any) => ({
        date: a.createdAt,
        symptoms: a.primarySymptoms,
        urgencyLevel: a.severity,
        recommendation: a.recommendedAction,
      })),
      recentLabReports: labReports.slice(0, 3).map((r: any) => ({
        fileName: r.fileName,
        date: r.testDate,
        summary: r.overallSummary,
        results: r.results?.slice(0, 8),
      })),
      recentConsultationTopics: conversations.slice(0, 5).map((c: any) => ({
        title: c.title,
        lastUpdated: c.updatedAt,
      })),
      questionsForDoctor: [
        'How do my recent health journal vitals compare to my long-term baseline?',
        'Do any reported symptoms indicate a need for targeted screening?',
        'Are my current lifestyle, sleep, and hydration habits appropriate for my health profile?',
      ],
      trustedSources: [
        'World Health Organization (WHO)',
        'Centers for Disease Control and Prevention (CDC)',
        'NIH / MedlinePlus',
        'National Health Service (NHS)',
      ],
      legalDisclaimer: 'MEDICAL DISCLAIMER: This document is an automated health awareness summary generated by Swasth AI 2.0 for personal educational reference only. It does NOT constitute a clinical diagnosis, medical opinion, prescription, or doctor-patient relationship. Bring this summary to your licensed healthcare provider for clinical evaluation.',
    };

    return NextResponse.json({ success: true, report: summary });
  } catch (error) {
    console.error('Report generation error:', error);
    return NextResponse.json({ error: 'Failed to generate health summary report' }, { status: 500 });
  }
}
